/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ithemba.ray_of_hope;

import javax.swing.JOptionPane;

/**
 *
 * @author Siviwe
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     * @param strUser
     */
    public frmMain(String strUser) {
        initComponents();
        this.setTitle("Ithemba - Ray of Hope Application Window");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        mUserAccessControl(strUser);
    }
    
    private void mUserAccessControl(String strUser) {
        switch(strUser) {
            case "Administrator":
                btnViewCovers.setVisible(true);
                btnCoverManagement.setVisible(true);
                btnRegAndManagePolicy.setVisible(true);
                btnViewAndSearchPrincipal.setVisible(true);
                btnManageBeneficiaries.setVisible(true);
                btnViewBeneficiaries.setVisible(true);
                btnCreateAccount.setVisible(false);
                btnUpdateAccount.setVisible(true);
                btnDeleteAccount.setVisible(true);
                btnLogout.setVisible(true);
                break;
                
            case "User/Client":
                btnViewCovers.setVisible(true);
                btnCoverManagement.setVisible(false);
                btnRegAndManagePolicy.setVisible(true);
                btnViewAndSearchPrincipal.setVisible(true);
                btnManageBeneficiaries.setVisible(true);
                btnViewBeneficiaries.setVisible(true);
                btnCreateAccount.setVisible(false);
                btnUpdateAccount.setVisible(true);
                btnDeleteAccount.setVisible(true);
                btnLogout.setVisible(true);
                btnViewAndSearchPrincipal.setText("View Your Policy");
                this.pack();
                break;
                
            case "Default Admin":
                btnViewCovers.setVisible(true);
                btnCoverManagement.setVisible(true);
                btnRegAndManagePolicy.setEnabled(false);
                btnViewAndSearchPrincipal.setEnabled(false);
                btnManageBeneficiaries.setEnabled(false);
                btnViewBeneficiaries.setEnabled(false);
                btnCreateAccount.setVisible(true);
                btnUpdateAccount.setEnabled(false);
                btnDeleteAccount.setEnabled(false);
                btnLogout.setVisible(true);
                break;
        }
    }
    
    private void mDeleteLoginAccount() {
        clsDatabaseInterface databaseInterface = new clsDatabaseInterface();
        frmLogin frmLogin = new frmLogin();
        
        if(databaseInterface.mGetField("SELECT Role FROM Users_Login WHERE ID="+frmLogin.mGetLoggedInUser()).equals("User/Client")) {
                            
                databaseInterface.mDeleteRecord("DELETE FROM Beneficiaries WHERE PM_ID_Num="+
                        databaseInterface.mGetField("SELECT ID_NUM FROM Principal_Members WHERE ACC_ID ="+frmLogin.mGetLoggedInUser()));
                
                databaseInterface.mDeleteRecord("DELETE FROM Principal_Members WHERE ID_Num ="+
                        databaseInterface.mGetField("SELECT ID_NUM FROM Principal_Members WHERE ACC_ID ="+frmLogin.mGetLoggedInUser()));
            
        } 
        databaseInterface.mDeleteRecord("DELETE FROM Users_Login WHERE ID="+frmLogin.mGetLoggedInUser());
        
        JOptionPane.showMessageDialog(this, "Your login account has been deleted. \nYou will be logged out.", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        frmLogin.mSetLoggedInUser(0);
        frmLogin.mSetPrincipalIDNo(0L);
        frmLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMainPanel = new javax.swing.JPanel();
        jpContainingPanel = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        jpCoversPanel = new javax.swing.JPanel();
        lblCovers = new javax.swing.JLabel();
        btnCoverManagement = new javax.swing.JButton();
        btnViewCovers = new javax.swing.JButton();
        jpPolicyManagement = new javax.swing.JPanel();
        lblPolicyManagement = new javax.swing.JLabel();
        btnRegAndManagePolicy = new javax.swing.JButton();
        btnManageBeneficiaries = new javax.swing.JButton();
        btnViewAndSearchPrincipal = new javax.swing.JButton();
        btnViewBeneficiaries = new javax.swing.JButton();
        jpManageLoginAccount = new javax.swing.JPanel();
        lblLoginAccount = new javax.swing.JLabel();
        btnUpdateAccount = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMainPanel.setBackground(new java.awt.Color(204, 0, 0));

        jpContainingPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("Ithemba - Ray of Hope");

        jpCoversPanel.setBackground(new java.awt.Color(153, 153, 153));

        lblCovers.setBackground(new java.awt.Color(255, 255, 255));
        lblCovers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCovers.setForeground(new java.awt.Color(255, 255, 255));
        lblCovers.setText("Covers");

        btnCoverManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnCoverManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCoverManagement.setText("Manage Covers");
        btnCoverManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoverManagementActionPerformed(evt);
            }
        });

        btnViewCovers.setBackground(new java.awt.Color(255, 255, 255));
        btnViewCovers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewCovers.setText("View Covers");
        btnViewCovers.setToolTipText("");
        btnViewCovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoversActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCoversPanelLayout = new javax.swing.GroupLayout(jpCoversPanel);
        jpCoversPanel.setLayout(jpCoversPanelLayout);
        jpCoversPanelLayout.setHorizontalGroup(
            jpCoversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCoversPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCoversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCovers)
                    .addComponent(btnCoverManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCovers, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCoversPanelLayout.setVerticalGroup(
            jpCoversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCoversPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCovers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCovers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnCoverManagement)
                .addContainerGap())
        );

        jpPolicyManagement.setBackground(new java.awt.Color(153, 153, 153));

        lblPolicyManagement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPolicyManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblPolicyManagement.setText("Policy Management");

        btnRegAndManagePolicy.setBackground(new java.awt.Color(255, 255, 255));
        btnRegAndManagePolicy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegAndManagePolicy.setText("Register & Manage Policy");
        btnRegAndManagePolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAndManagePolicyActionPerformed(evt);
            }
        });

        btnManageBeneficiaries.setBackground(new java.awt.Color(255, 255, 255));
        btnManageBeneficiaries.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageBeneficiaries.setText("Manage Beneficiaries");
        btnManageBeneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBeneficiariesActionPerformed(evt);
            }
        });

        btnViewAndSearchPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAndSearchPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewAndSearchPrincipal.setText("View & Search Principal");
        btnViewAndSearchPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAndSearchPrincipalActionPerformed(evt);
            }
        });

        btnViewBeneficiaries.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBeneficiaries.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewBeneficiaries.setText("View Beneficiaries");
        btnViewBeneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBeneficiariesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPolicyManagementLayout = new javax.swing.GroupLayout(jpPolicyManagement);
        jpPolicyManagement.setLayout(jpPolicyManagementLayout);
        jpPolicyManagementLayout.setHorizontalGroup(
            jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPolicyManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPolicyManagement)
                    .addComponent(btnRegAndManagePolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageBeneficiaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewAndSearchPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewBeneficiaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPolicyManagementLayout.setVerticalGroup(
            jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPolicyManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPolicyManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegAndManagePolicy)
                    .addComponent(btnViewAndSearchPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPolicyManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageBeneficiaries)
                    .addComponent(btnViewBeneficiaries))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpManageLoginAccount.setBackground(new java.awt.Color(153, 153, 153));

        lblLoginAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAccount.setText("Manage Your Login Account");

        btnUpdateAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateAccount.setText("Update Account");
        btnUpdateAccount.setToolTipText("");
        btnUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountActionPerformed(evt);
            }
        });

        btnDeleteAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        btnCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setMaximumSize(new java.awt.Dimension(177, 23));
        btnCreateAccount.setMinimumSize(new java.awt.Dimension(177, 23));
        btnCreateAccount.setPreferredSize(new java.awt.Dimension(177, 23));
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setMaximumSize(new java.awt.Dimension(177, 23));
        btnLogout.setMinimumSize(new java.awt.Dimension(177, 23));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpManageLoginAccountLayout = new javax.swing.GroupLayout(jpManageLoginAccount);
        jpManageLoginAccount.setLayout(jpManageLoginAccountLayout);
        jpManageLoginAccountLayout.setHorizontalGroup(
            jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpManageLoginAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpManageLoginAccountLayout.createSequentialGroup()
                        .addComponent(lblLoginAccount)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpManageLoginAccountLayout.createSequentialGroup()
                        .addGroup(jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(btnDeleteAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpManageLoginAccountLayout.setVerticalGroup(
            jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpManageLoginAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateAccount)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpManageLoginAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAccount)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ithemba/ray_of_hope/icon.jpg"))); // NOI18N

        javax.swing.GroupLayout jpContainingPanelLayout = new javax.swing.GroupLayout(jpContainingPanel);
        jpContainingPanel.setLayout(jpContainingPanelLayout);
        jpContainingPanelLayout.setHorizontalGroup(
            jpContainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContainingPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jpContainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpManageLoginAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPolicyManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCoversPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(jpContainingPanelLayout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(lblHeading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContainingPanelLayout.setVerticalGroup(
            jpContainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContainingPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHeading)
                .addGap(28, 28, 28)
                .addGroup(jpContainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpContainingPanelLayout.createSequentialGroup()
                        .addComponent(jpCoversPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jpPolicyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jpManageLoginAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jpMainPanelLayout = new javax.swing.GroupLayout(jpMainPanel);
        jpMainPanel.setLayout(jpMainPanelLayout);
        jpMainPanelLayout.setHorizontalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpContainingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jpMainPanelLayout.setVerticalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpContainingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoverManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoverManagementActionPerformed
        new frmCovers(this).setVisible(true);
    }//GEN-LAST:event_btnCoverManagementActionPerformed

    private void btnViewCoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoversActionPerformed
        new frmView(this, "Covers").setVisible(true);
    }//GEN-LAST:event_btnViewCoversActionPerformed

    private void btnRegAndManagePolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAndManagePolicyActionPerformed
        new frmRegisterAndManagePolicies(this).setVisible(true);
    }//GEN-LAST:event_btnRegAndManagePolicyActionPerformed

    private void btnViewAndSearchPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAndSearchPrincipalActionPerformed
        new frmView(this, "Principals").setVisible(true);
    }//GEN-LAST:event_btnViewAndSearchPrincipalActionPerformed

    private void btnManageBeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBeneficiariesActionPerformed
        new frmBeneficiaries(this).setVisible(true);
    }//GEN-LAST:event_btnManageBeneficiariesActionPerformed

    private void btnViewBeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBeneficiariesActionPerformed
        new frmView(this, "Beneficiaries").setVisible(true);
    }//GEN-LAST:event_btnViewBeneficiariesActionPerformed

    private void btnUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountActionPerformed
        new frmLoginAccount(this, "Update").setVisible(true);
    }//GEN-LAST:event_btnUpdateAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        mDeleteLoginAccount();
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        new frmLoginAccount(this, "Sign Up").setVisible(true);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        frmLogin frmLogin = new frmLogin();
        frmLogin.mSetLoggedInUser(0);
        frmLogin.mSetPrincipalIDNo(0L);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoverManagement;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageBeneficiaries;
    private javax.swing.JButton btnRegAndManagePolicy;
    private javax.swing.JButton btnUpdateAccount;
    private javax.swing.JButton btnViewAndSearchPrincipal;
    private javax.swing.JButton btnViewBeneficiaries;
    private javax.swing.JButton btnViewCovers;
    private javax.swing.JPanel jpContainingPanel;
    private javax.swing.JPanel jpCoversPanel;
    private javax.swing.JPanel jpMainPanel;
    private javax.swing.JPanel jpManageLoginAccount;
    private javax.swing.JPanel jpPolicyManagement;
    private javax.swing.JLabel lblCovers;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLoginAccount;
    private javax.swing.JLabel lblPolicyManagement;
    // End of variables declaration//GEN-END:variables
}
